"""Migration reversibility and model/migration drift — PostgreSQL lane only.

The SQLite lane builds its schema with ``Base.metadata.create_all``, so nothing
there would notice if the migration and the models drifted apart. These tests
close that gap (master §2): the baseline must round-trip
``upgrade -> downgrade -> upgrade`` and ``alembic check`` must report no diff.

Skipped automatically unless ``TEST_DATABASE_URL`` is set.
"""

import asyncio
import os
from argparse import Namespace
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.ext.asyncio import create_async_engine

pytestmark = pytest.mark.postgres

BACKEND_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_TABLES = {"users", "todo_lists", "todos", "tags", "todo_tags"}


def _alembic_config(url: str) -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "migrations"))
    # env.py prefers an explicit `-x url=…` over the app's DATABASE_URL.
    config.cmd_opts = Namespace(x=[f"url={url}"])
    return config


def _run(fn, *args, **kwargs):
    """Alembic's env.py calls ``asyncio.run``; give it a loop-free thread."""
    return asyncio.to_thread(fn, *args, **kwargs)


@pytest.fixture
def migration_url(db_url: str) -> str:
    assert db_url.startswith("postgresql"), "postgres-marked test on the wrong lane"
    return db_url


@pytest.fixture
async def clean_database(migration_url: str):
    """These tests own the whole schema, so start and finish from ``base``."""
    config = _alembic_config(migration_url)
    engine = create_async_engine(migration_url)
    async with engine.begin() as connection:
        await connection.execute(sa.text("DROP SCHEMA public CASCADE"))
        await connection.execute(sa.text("CREATE SCHEMA public"))
    await engine.dispose()
    yield config
    await _run(command.downgrade, config, "base")


async def _table_names(url: str) -> set[str]:
    engine = create_async_engine(url)
    try:
        async with engine.connect() as connection:
            return set(
                await connection.run_sync(
                    lambda sync_conn: sa.inspect(sync_conn).get_table_names()
                )
            )
    finally:
        await engine.dispose()


async def test_upgrade_downgrade_upgrade_round_trips(
    clean_database, migration_url: str
) -> None:
    config = clean_database

    await _run(command.upgrade, config, "head")
    assert SCHEMA_TABLES <= await _table_names(migration_url)

    await _run(command.downgrade, config, "base")
    remaining = await _table_names(migration_url)
    # Nothing of ours may survive a downgrade (only alembic's own bookkeeping).
    assert SCHEMA_TABLES & remaining == set(), remaining

    await _run(command.upgrade, config, "head")
    assert SCHEMA_TABLES <= await _table_names(migration_url)


async def test_alembic_check_reports_no_drift(clean_database) -> None:
    """The migration and the ORM models must describe the same schema."""
    config = clean_database
    await _run(command.upgrade, config, "head")
    try:
        await _run(command.check, config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations have drifted: {exc}")


async def test_priority_check_constraint_is_enforced(
    clean_database, migration_url: str
) -> None:
    """The non-native enum must still reject an out-of-range value."""
    config = clean_database
    await _run(command.upgrade, config, "head")

    engine = create_async_engine(migration_url)
    try:
        async with engine.begin() as connection:
            user_id = await connection.scalar(
                sa.text(
                    "INSERT INTO users (id, email, password_hash, created_at,"
                    " updated_at) VALUES (gen_random_uuid(), 'ck@example.com', '!',"
                    " now(), now()) RETURNING id"
                )
            )
            list_id = await connection.scalar(
                sa.text(
                    "INSERT INTO todo_lists (id, user_id, name, is_default,"
                    " created_at, updated_at) VALUES (gen_random_uuid(), :uid,"
                    " 'Inbox', true, now(), now()) RETURNING id"
                ),
                {"uid": user_id},
            )
        async with engine.begin() as connection:
            with pytest.raises(Exception) as excinfo:
                await connection.execute(
                    sa.text(
                        "INSERT INTO todos (id, user_id, list_id, title, completed,"
                        " priority, created_at, updated_at) VALUES"
                        " (gen_random_uuid(), :uid, :lid, 'x', false, 'urgent',"
                        " now(), now())"
                    ),
                    {"uid": user_id, "lid": list_id},
                )
            assert "ck_todos_priority" in str(excinfo.value)
    finally:
        await engine.dispose()


def test_migration_directory_has_exactly_one_baseline() -> None:
    versions = sorted((BACKEND_ROOT / "migrations" / "versions").glob("*.py"))
    assert [path.name for path in versions] == ["0001_initial_schema.py"]


def test_database_url_is_never_committed_in_alembic_ini() -> None:
    """Credentials come from the environment, never from a committed file."""
    text = (BACKEND_ROOT / "alembic.ini").read_text(encoding="utf-8")
    assert "sqlalchemy.url =" not in text
    assert os.environ.get("TEST_DATABASE_URL") not in text
